/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { AdminFacet, AdminFacetInterface } from "../AdminFacet";

const _abi = [
  {
    inputs: [],
    name: "withdrawProtocolFees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610363806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80638795cccb14610030575b600080fd5b61003861003a565b005b6100426100fb565b600080600201549050600080600201819055506000800160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1663a9059cbb33836040518363ffffffff1660e01b81526004016100b492919061021d565b6020604051808303816000875af11580156100d3573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906100f79190610283565b5050565b610103610196565b60030160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614610194576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161018b9061030d565b60405180910390fd5b565b6000807fc8fcad8db84d3cc18b4c41d551ea0ee66dd599cde068d998e57d5e09332c131c90508091505090565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006101ee826101c3565b9050919050565b6101fe816101e3565b82525050565b6000819050919050565b61021781610204565b82525050565b600060408201905061023260008301856101f5565b61023f602083018461020e565b9392505050565b600080fd5b60008115159050919050565b6102608161024b565b811461026b57600080fd5b50565b60008151905061027d81610257565b92915050565b60006020828403121561029957610298610246565b5b60006102a78482850161026e565b91505092915050565b600082825260208201905092915050565b7f4d75737420626520636f6e7472616374206f776e657200000000000000000000600082015250565b60006102f76016836102b0565b9150610302826102c1565b602082019050919050565b60006020820190508181036000830152610326816102ea565b905091905056fea26469706673582212209cc8eb69e2e3bf187eff554e9ea41b3b28862fb232aabd58db06fe26aeb53a9b64736f6c634300080d0033";

export class AdminFacet__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<AdminFacet> {
    return super.deploy(overrides || {}) as Promise<AdminFacet>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): AdminFacet {
    return super.attach(address) as AdminFacet;
  }
  connect(signer: Signer): AdminFacet__factory {
    return super.connect(signer) as AdminFacet__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AdminFacetInterface {
    return new utils.Interface(_abi) as AdminFacetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AdminFacet {
    return new Contract(address, _abi, signerOrProvider) as AdminFacet;
  }
}
